services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  discovery-service:
    build: ./discovery_service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  main-service:
    build: ./main_service
    container_name: main-service
    depends_on:
      - discovery-service
      - postgresql
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - backend

  workload-service:
    build: ./workload_service
    container_name: workload-service
    depends_on:
      - discovery-service
      - redis
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka
      SPRING_REDIS_HOST: redis
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
