services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - backend

  activemq:
    image: rmohr/activemq
    container_name: activemq
    environment:
      ACTIVEMQ_USER: ${SPRING_ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${SPRING_ACTIVEMQ_PASSWORD}
    ports:
      - "8161:8161"  # Web console
      - "61616:61616" # JMS
    networks:
      - backend

networks:
  backend:
    driver: bridge
