server:
  port: 8082

spring:
  application:
    name: workload-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true
