seed.file.path=src/main/resources/seed.json

# Should be in .env but i put it here for simplicity for now : )
spring.datasource.url=jdbc:postgresql://localhost:5432/gym
spring.datasource.username=admin
spring.datasource.password=adminpassword

spring.mvc.servlet.path=/api/v1