server:
  port: 8082

spring:
  application:
    name: workload-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  activemq:
    broker-url: ${SPRING_ACTIVEMQ_BROKER_URL}
    user: ${SPRING_ACTIVEMQ_USER}
    password: ${SPRING_ACTIVEMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true
