server:
  port: 8082

spring:
  application:
    name: workload-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

  activemq:
    broker-url: ${SPRING_ACTIVEMQ_BROKER_URL}
    user: ${SPRING_ACTIVEMQ_USER}
    password: ${SPRING_ACTIVEMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true
